language: julia
os:
  - linux
julia:
  - 0.7
notifications:
  email: false
git:
  depth: 99999999
# cache:
#   directories:
#   - downloads
env:
  global:
    - BINARYBUILDER_DOWNLOADS_CACHE=downloads
    - BINARYBUILDER_ROOTFS_DIR=rootfs
sudo: required
before_script:
  - julia --color=yes -e 'using Pkg;
      Pkg.add(PackageSpec(name="BinaryProvider", rev="master"));
      Pkg.add(PackageSpec(name="BinaryBuilder", rev="master"))'
script:
  - BINARYBUILDER_AUTOMATIC_APPLE=true julia --color=yes build_tarballs.jl
deploy:
  provider: s3
  access_key_id: AKIAJXUT2HDDBVLZHVNA
  secret_access_key:
    secure: "FSDER83fYu1stpPH3anX19eWw0reZUHt5czHolpKXc3Tg1GAB6mCPYztTZUffqTan6jJVuKaXryoaDRxpZEvCMbp5wB252T+HzeUXnIsDmxE50ziHXnv5xkGS1jo3jMkXcLl7oJZHCSLHtoaMlObtm9aMm0Ufd+VcUUoSM8s8ilnx/K0xtEH/BOgLNj9SlpLa6eers6hvKwEWsuZbvCtdFlOi55N5HDGUGK8c6PVv+CyLoQYO5xj5DLSLRMGg8Ive/WwaJoyxv6Jo6lYCVdyW4FagfvNzfRDhkvSIM3uoODonkFAQPfROYDANOkwm+0YXIIKEeoJ1oCGhSCVifHAkpU3rZ1TvmMJeaMqZKYQOl0nwrHPq6rhdfsATZbX0bzI5204E1ZuoDFWRGbXgNu5nq6sK5sT6rM5k/zkTtBB0DwnZPpo0sI7SN7IwY//TjPaABOU7y8wBhqeqUMynIEQi2w8y1Pe8Ox6XZ8wSUEHGiyRF9IC6wipucdnQmX9gQGAxzUH+pYl6QLeKn4dBxT9525eqnqt+7hO3wUneRwhWYeZ92pZ/l8JVfkYvxNQ+nfJMf1v3rrxYNrAFEX/34jdEc8e3WuY0Rc/kP9MJuA+8JXx3KJ1nBLJIduxANMtYeGlpMOhGcPzZD3N7CF9e4Jmh0nXBVOBwYg/JAxfNYho+jQ="
  bucket: ringbuffersbuilder
  local_dir: products
  acl: public_read
  skip_cleanup: true
  region: us-east-2
  on:
    repo: JuliaAudio/RingBuffersBuilder
