language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email: false
git:
  depth: 99999999
cache:
  directories:
    - downloads
env:
  global:
    - BINARYBUILDER_DOWNLOADS_CACHE=downloads
    - BINARYBUILDER_ROOTFS_DIR=rootfs
sudo: required

# Before anything else, get the latest versions of things
before_script:
  - julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryProvider.jl")'
  - julia -e 'Pkg.clone("https://github.com/JuliaPackaging/BinaryBuilder.jl"); Pkg.build()'

script:
  - julia build_tarballs.jl

# deploy:
#   provider: releases
#   file_glob: true
#   file: products/*.tar.gz
#   skip_cleanup: true
#   on:
#     repo: JuliaAudio/RingBuffersBuilder
#     tags: true
